// Super simple Google Photos configuration
// This was auto-generated by the setup wizard!

export interface GooglePhotosConfig {
  clientId: string;
  apiKey: string;
  albumId?: string;
}

export const GOOGLE_PHOTOS_CONFIG: GooglePhotosConfig = {
  clientId: '534397866659-pohkgifi20sighbs4cdmmhupj2k4jprf.apps.googleusercontent.com',
  apiKey: 'AIzaSyDvznYBe96bcb6aVXwVsh7MqywHsFWtFss',
  albumId: 'AF1QipOWienDlDvR_qqwMmzuUXlL3iOEwX9G8Kp0l3Nt' // Using specific album
};

// 🎉 Setup complete! Go click "Sync Google Photos" in the app!