"""Generate the client spell mirror from the Python source of truth.

Python (undercity_data.SPELLS/GRIMOIRES/BIOME_SPELLS) is authored; this renders
src/app/undercity/data/spells.generated.ts (data arrays only). The hand-written
spells.ts keeps the types + helpers and re-exports these arrays. The
copies-match pytest in tests/test_spells_generated.py fails while they differ.

Run after editing the spell tables:  python infrastructure/lambda/sync_spells.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import undercity_data as data  # noqa: E402

OUT = (Path(__file__).resolve().parents[2]
       / 'src' / 'app' / 'undercity' / 'data' / 'spells.generated.ts')

# Client SpellInfo carries no buffKind/blurb (server-only); grimoire desc is the
# Python blurb. Optional numeric fields are omitted when absent, matching style.
_SPELL_OPTIONAL = ('range', 'maxValue', 'power')


def _ts(value):
    """A TS string literal: double-quoted, unicode preserved, properly escaped."""
    return json.dumps(value, ensure_ascii=False)


def _spell_line(spell_id, sp):
    parts = [f'id: {_ts(spell_id)}', f'name: {_ts(sp["name"])}',
             f'category: {_ts(sp["category"])}', f'tier: {sp["tier"]}',
             f'cooldownMin: {sp["cooldownMin"]}', f'effect: {_ts(sp["effect"])}']
    for opt in _SPELL_OPTIONAL:
        if opt in sp:
            parts.append(f'{opt}: {sp[opt]}')
    parts.append(f'desc: {_ts(sp["desc"])}')
    parts.append(f'icon: {_ts(sp["icon"])}')
    return '  { ' + ', '.join(parts) + ' },'


def _grim_line(grim_id, g):
    spells = '[' + ', '.join(_ts(s) for s in g['spells']) + ']'
    parts = [f'id: {_ts(grim_id)}', f'name: {_ts(g["name"])}', f'tier: {g["tier"]}',
             f'cost: {g["cost"]}', f'spells: {spells}', f'desc: {_ts(g["blurb"])}']
    return '  { ' + ', '.join(parts) + ' },'


def render():
    lines = [
        '// AUTO-GENERATED by infrastructure/lambda/sync_spells.py — DO NOT EDIT.',
        '// Edit the Python tables in undercity_data.py, then re-run sync_spells.py.',
        "import type { SpellInfo, GrimoireInfo } from './spells';",
        '',
        'export const SPELLS: SpellInfo[] = [',
    ]
    lines += [_spell_line(sid, sp) for sid, sp in data.SPELLS.items()]
    lines += ['];', '', 'export const GRIMOIRES: GrimoireInfo[] = [']
    lines += [_grim_line(gid, g) for gid, g in data.GRIMOIRES.items()]
    lines += ['];', '', 'export const BIOME_SPELLS: Record<string, string> = {']
    lines += [f'  {_ts(biome)}: {_ts(spell_id)},'
              for biome, spell_id in data.BIOME_SPELLS.items()]
    lines += ['};', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    OUT.write_text(render(), encoding='utf-8', newline='\n')
    print(f'wrote {OUT}')
